version: "3.8"
services:
  hub:
    image: jetbrains/hub:2020.1.12693
    ports:
      - 8082:8080
    entrypoint: ["/bin/bash", "/hub-entrypoint.sh"]
    environment:
      HUB_BASE_URL: "${HUB_BASE_URL}"
      HUB_ADMIN_LOGIN: "${HUB_ADMIN_LOGIN}"
      HUB_ADMIN_PASSWORD: "${HUB_ADMIN_PASSWORD}"
    volumes:
      - ./hub-entrypoint.sh:/hub-entrypoint.sh
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  datalore:
    image: jetbrains/datalore-server:v0.3.0
    entrypoint: ["/bin/bash", "/datalore-entrypoint.sh"]
    ports:
      - 8080:8080
      - 5050:5050
      - 5060:5060
    volumes:
      - ${KUBECONFIG_FILE}:/home/datalore/.kube/config
      - ./datalore-entrypoint.sh:/datalore-entrypoint.sh
      - ./agents_config.yaml:/etc/datalore/agents-config/agents_config.yaml
      - ./plans_config.yaml:/etc/datalore/plans-config/plans_config.yaml
      - ./envs:/etc/datalore/environment_info

    environment:
      FRONTEND_URL: "${DATALORE_URL}"
      DATALORE_BASE_URL: "${DATALORE_URL}"
      DATALORE_INTERNAL_HOST: "${DATALORE_INTERNAL_HOST}"
      HUB_PUBLIC_BASE_URL: "${HUB_BASE_URL}/hub/"
      HUB_FORCE_EMAIL_VERIFICATION: "${HUB_FORCE_EMAIL_VERIFICATION}"
      MAX_HEAP_SIZE: "${DATALORE_MAX_HEAP_SIZE}"
      DB_PASSWORD: "${DB_PASSWORD}"
      PASSWORD_SECRET: "${PASSWORD_SECRET}"
      HUB_DATALORE_SERVICE_SECRET: "${HUB_DATALORE_SERVICE_SECRET}"
      HUB_ADMIN_LOGIN: "${HUB_ADMIN_LOGIN}"
      HUB_ADMIN_PASSWORD: "${HUB_ADMIN_PASSWORD}"
      HUB_DATALORE_SERVICE_ID: "datalore"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      HUB_BASE_URL: "http://hub"
      ENABLE_PLANS: "false"
      MAIL_ENABLED: "false"
      DEFAULT_BASE_ENV_NAME: "default"
      DEFAULT_PACKAGE_MANAGER: "pip"
